[package]
name = "foxbox_taxonomy"
version = "0.1.2"
authors = ["David Rajchenbach-Teller <dteller@mozilla.com>"]

[dependencies]
serde = "0.6.13"
serde_json = "0.6.0"
serde_macros = "0.6.14"
serde_utils = "^0.1"
chrono = "0.2.19"
